# standard jekyll configuration

permalink: /blog/:title
pygments: false
exclude: ['README.md']

# configuration required for some pages

domain: olliebennett.github.io
title: Ollie Bennett
author: Ollie Bennett
email: olliebennett@gmail.com

collections:
  projects:
    output: true
    permalink: projects/:slug/
    order:
      - student_spreadsheet.md
      - qrupted.md
      - coursecalc.md
