# standard jekyll configuration

highlighter: false
include: ['_redirects']
exclude: ['README.md']

# configuration required for some pages

domain: olliebennett.co.uk
title: Ollie Bennett
author: Ollie Bennett
email: olliebennett@gmail.com

collections:
  thoughts:
    output: true
    permalink: thoughts/:slug/
  projects:
    output: true
    permalink: projects/:slug/
