# standard jekyll configuration

highlighter: false
exclude: ['README.md']

# configuration required for some pages

domain: olliebennett.github.io
title: Ollie Bennett
author: Ollie Bennett
email: olliebennett@gmail.com

collections:
  projects:
    output: true
    permalink: projects/:slug/
